### ISSUE TITLE
Left Panel - Layers Tab

### ISSUE THREAD

**Issue by SwampGuzzler** [wri/gfw-mapbuilder#716]
- [X] Connect Layers Tab to Redux/Resources
- [X] Layer GROUP for each Group in Resources + the Layers from webmap
- [X] Checkbox per layer
- [X] Checkbox's `checked` based on associated layer's visibility (via Redux's `activeLayers`)
- [X] Style left panel (scaffolding) (#875 )
- [x] Style left panel (pixel-by-pixel detail)
- [x] Style left panel 'i' info content modal (pixel-by-pixel detail) #923 
- [x] Clicking on "i" icon shows a modal with additional information for the layer #922 
- [x] Clicking on "i" icon of `WEMAP_GROUP` shows a modal with additional information for the layer 
- [x] Layer controls display layer subtitle below its name #925 
- [x] Certain layers control canopy density > density slider implementation #884
- [x] Investigate layer density control list #886
- [x] Certain layers have start and end dates #929 
- [x] Certain layers have time period pickers (24H, 48H) #919 
- [x] Glad alert layer have unconfirmed alert toggle
- [x] Cover loss has dual slider

**Comment by eyosef** [comment]
> * [x]  Clicking on "i" icon shows a modal with additional information for the layer

Updating this ticket to note that `WEBMAP_GROUP` is a type that doesn't have metadata to populate the `InfoContent` component. Since PROD has popup content for this layer group, we'll have to dig into this in a separate feature branch/PR to maintain SOC

Decision-tree @csphang provided to guide our approach;

**Webmap groups (for layers which come from webmap group, the following logic is used):**
- [ ] Full extended metadata from ArcGIS Online is used if the metadata is defined in ArcGIS Online for the item (https://doc.arcgis.com/en/arcgis-online/manage-data/metadata.htm)
- [x] If extended metadata is not defined, then the description and summary are used instead #932 
- [ ] If the layer added is an ArcGIS Feature Service or MapService and the service was added to the map via a URL, the metadata from the layer itself will be used.

**Non-Webmap groups (for layers which are configured through the configuration, the following logic is used):**
- [ ] If the Technical name for a layer is specified, then the metadata for the layer will be pulled from the GFW Metdata API
- [ ] If the layer is stored in the API, and includes a metadata URL the source used will be the metadata
- [x] If the technical name is not specified and the data is hosted through ArcGIS (Feature or MapService Layer) metadata from the layer will be used. Make sure your layer includes metadata before you publish it #922

**Comment by eyosef** [comment]
<img width="479" alt="Screen Shot 2020-03-25 at 4 00 36 PM" src="https://user-images.githubusercontent.com/9040867/77580270-1abc3f00-6eb2-11ea-8e49-4e030180604a.png">

Updating this ticket to note that we still need to fix the button of `InfoContent.tsx` to the bottom of the modal
