### ISSUE TITLE
Uploading a shapefile UI and logic

### ISSUE THREAD

**Issue by eyosef** [wri/gfw-mapbuilder#848]
- [x] User is able to EDIT/SAVE/DELETE uploaded geometry (same functionality as with the draw polygon widget) #972 
- [x] EDIT/DELETE button UI matches comps #975 
- [x] Shapefile upload component basic styling #851
- [x] Shapefile upload component exists in pen widget #849
- [x] Shapefile upload component exists in analysis (default) tab #854 
- [x] User can upload geojson file #859 
- [x] When uploaded, make API call to GFW endpoint to convert https://production-api.globalforestwatch.org/v1/ogr/convert ( PROD in `upload.js`) it returns GEOJSON #859 
- [x] Then we convert a shapefile to geojson, then convert it to arcgis (we can utilize util functions from PROD `arcgis-to-jsonjs` #859 
- [x] We draw that shape on the map. And zoom to it. #859 
- [x] Opens analysis tab and populates data tab with content #860
- [x] Conditionally closes modal #860
- [x] Clear previous graphic before adding a graphic to the mapview #866 
- [x] Register geometry with the geostore and add it to the active features array #869
