### ISSUE TITLE
MyGFW Subscriptions UI and logic

### ISSUE THREAD

**Issue by eyosef** [wri/gfw-mapbuilder#861]
Part of: #858
- [x] delete subscriptions (#862 )
- [x] onClick of world icon, go to the subscription location (#864 )
- [x] apply styling scaffolding to align with comps (#874 )
- [x] match comps perfectly (last step) (#1010 )
- [x] update DBs by toggling on/off layers (#865 )
- [x] ~~resolve [edge cases](https://github.com/wri/gfw-mapbuilder/pull/864#issuecomment-592728489) ID'd in `zoomToSubscription()`~~ This edge case can no longer be reproduced
