### ISSUE TITLE
Layer transparency slider

### ISSUE THREAD

**Issue by vaidotasp** [wri/gfw-mapbuilder#891]
Utilizing rc-slider lib create a component that modifies layer transparency

- [x] Range is from 0 to 1, #893 
- [x] Default value to be determined from redux array `allAvailableLayers`! #893 
    - Quick note; Looks like `LayerTransparencySlider` is receiving properties of `allAvailableLayers` from `GenericLayerContent`!
- [x] Styling close but not necessarily pixel by pixel to PROD #893 
- [x] Slider is visible only when layer is visible #893 
- [x] All layers have transparency sliders #893
