### ISSUE TITLE
Layer Tab - TimeSlider component

### ISSUE THREAD

**Issue by vaidotasp** [wri/gfw-mapbuilder#892]
- [x] using rc-slider component of dual marks - http://react-component.github.io/slider/examples/range.html #894 
- [x] default range is hardcoded from 2000 to 2018. #892 
- [x] updating dates seem to be modifying `options` property on BaseTileLayers and calling `refresh()` method on it (see example of updating canopy density in mapController) #900 
- [x] Play button and play functionality. Hitting play starts  going from lowest year to highest year, updating map. User can pause playing. #900 
- [x] UI - slider should have marks denoting the year (see below) #909 

![image](https://user-images.githubusercontent.com/12076555/76355819-57513d80-62eb-11ea-92e5-fb2080af58c8.png)
