### ISSUE TITLE
Reusable defined dates dropdown

### ISSUE THREAD

**Issue by eyosef** [wri/gfw-mapbuilder#915]
![Screen Shot 2020-03-20 at 3 05 23 PM](https://user-images.githubusercontent.com/9040867/77197856-48714480-6abc-11ea-977c-e95041544af4.png)

- [x] Create a reusable component with start/end dates #917 
- [x] Dynamically leverage across layers tab view #917 
- [x] Updating the dropdown updates the appropriate layer #919 
- [x] Toggling the feature layer is hooked up to sublayers #919 
- [x] Using the `layerVisibilitySlider` is hooked up to sublayers #919 
- [x] Updating the calendar updates the layer - also, `input type='date'` `min` is dynamically set #929 
- [x] Dynamically leverage in the analysis tab (workflow: user draws polygon, dropdown appears. Selecting certain options in the dropdown renders the start/end date component #952 
- [x] Styled to match comps #936

**Comment by eyosef** [comment]
> Dynamically leverage in the analysis tab (workflow: user draws polygon, dropdown appears. Selecting certain options in the dropdown renders the start/end date component

Just following up on this to clarify that the original comment was indicated the UI/logic below. This is only needed for GLAD alerts


<img width="348" alt="Screen Shot 2020-04-13 at 4 18 04 PM" src="https://user-images.githubusercontent.com/9040867/79157291-5c018980-7da2-11ea-840f-73e0b799ca68.png">

Implemented via #952
